// export const hotelsData = {
//   Bahrain: [
//     {
//       id: 1,
//       position: [26.2708, 50.6261],
//       name: "Islamabad Serena Hotel",
//       location: "Khaliq Uz Zaman Road, Islamabad",
//       price: 120,
//       image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
//       rating: 5,
//       description:
//         "Islamabad Serena Hotel is a commercial establishment that provides lodging, meals, and other services to guests, travelers, and tourists.",
//       facilities: [
//         "Restaurant & Bar",
//         "Airport Shuttle",
//         "Conference Hall",
//         "Laundry Service",
//         "Car Rental",
//       ],
//       roomImages: [
//         "https://static.cupid.travel/hotels/508614426.jpg",
//         "https://static.cupid.travel/hotels/518527047.jpg",
//         "https://static.cupid.travel/hotels/518526053.jpg",
//         "https://static.cupid.travel/hotels/491810902.jpg",
//         "https://static.cupid.travel/hotels/491176899.jpg",
//       ],
//       rooms: [
//         {
//           id: 101,
//           title: "1 x Deluxe Double Room, 1 Double Bed, Smoking",
//           fitForAdults: 2,
//           fitForChildren: 1,
//           price: 120.68,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 5,
//             size: "25 m²",
//             amenities: ["Minibar", "Shower", "Safety deposit box", "TV"],
//           },
//         },
//         {
//           id: 102,
//           title: "Executive Suite",
//           fitForAdults: 3,
//           fitForChildren: 2,
//           price: 180.99,
//           breakFast: false,
//           refund: false,
//           off: 8,
//           Cancelation: true,
//           oldprice: 90,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 3,
//             size: "40 m²",
//             amenities: ["Jacuzzi", "Balcony", "Flat-screen TV", "Work Desk"],
//           },
//         },
//       ],
//     },
//     {
//       id: 2,
//       position: [19.2708, 50.6261],
//       name: "Marriott Hotel, Islamabad",
//       location: "Agha Khan Road, Islamabad",
//       price: 90,
//       image:
//         "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=600&auto=format&fit=crop&q=60",
//       rating: 4,
//       description:
//         "Marriott Hotel, Islamabad is a commercial establishment that provides lodging, meals, and other services.",
//       facilities: [
//         "Free Wi-Fi",
//         "24/7 Room Service",
//         "Swimming Pool",
//         "Fitness Center",
//         "Spa & Wellness",
//       ],
//       roomImages: [
//         "https://static.cupid.travel/hotels/518527047.jpg",
//         "https://static.cupid.travel/hotels/508614426.jpg",
//         "https://static.cupid.travel/hotels/518526053.jpg",
//       ],
//       rooms: [
//         {
//           id: 201,
//           title: "Standard Room",
//           fitForAdults: 2,
//           fitForChildren: 0,
//           price: 90.5,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 50,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 10,
//             size: "20 m²",
//             amenities: ["Wi-Fi", "TV", "Private Bathroom"],
//           },
//         },
//         {
//           id: 202,
//           title: "Luxury Suite",
//           fitForAdults: 4,
//           fitForChildren: 2,
//           price: 150.7,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 360,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 2,
//             size: "60 m²",
//             amenities: ["Kitchenette", "Balcony", "Living Area", "Jacuzzi"],
//           },
//         },
//       ],
//     },
//   ],

//   Dubai: [
//     {
//       id: 1,
//       position: [26.1292, 50.555],
//       name: "Pearl Continental Lahore",
//       location: "Shahrah-e-Quaid-e-Azam, Lahore",
//       price: 50,
//       image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
//       rating: 2,
//       description:
//         "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
//       facilities: [
//         "Business Center",
//         "Concierge Service",
//         "Mini Bar in Rooms",
//         "Luggage Storage",
//         "Daily Housekeeping",
//       ],
//       roomImages: [
//         "https://static.cupid.travel/hotels/508614426.jpg",
//         "https://static.cupid.travel/hotels/518527047.jpg",
//       ],
//       rooms: [
//         {
//           id: 301,
//           title: "Classic Room",
//           fitForAdults: 2,
//           fitForChildren: 1,
//           price: 150.99,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 80,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 8,
//             size: "22 m²",
//             amenities: ["AC", "TV", "Private Bathroom"],
//           },
//         },
//         {
//           id: 302,
//           title: "Presidential Suite",
//           fitForAdults: 4,
//           fitForChildren: 3,
//           price: 50.99,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 40,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//         {
//           id: 303,
//           title: "Presidential Suite",
//           fitForAdults: 1,
//           fitForChildren: 0,
//           price: 80.99,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: false,
//           oldprice: 40,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//       ],
//     },

//     {
//       id: 2,
//       position: [28.1292, 52.555],
//       name: "Pearl Continental Lahore",
//       location: "Shahrah-e-Quaid-e-Azam, Lahore",
//       price: 10.99,
//       image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
//       rating: 2,
//       description:
//         "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
//       facilities: [
//         "Business Center",
//         "Concierge Service",
//         "Mini Bar in Rooms",
//         "Luggage Storage",
//         "Daily Housekeeping",
//       ],
//       roomImages: [
//         "https://static.cupid.travel/hotels/508614426.jpg",
//         "https://static.cupid.travel/hotels/518527047.jpg",
//       ],
//       rooms: [
//         // {
//         //   id: 301,
//         //   title: "Classic Room",
//         //   fitForAdults: 2,
//         //   fitForChildren: 1,
//         //   price: 150,
//         //   roomDetails: {
//         //     count: 8,
//         //     size: "22 m²",
//         //     amenities: ["AC", "TV", "Private Bathroom"],
//         //   },
//         // },
//         {
//           id: 302,
//           title: "Presidential Suite",
//           fitForAdults: 2,
//           fitForChildren: 3,
//           price: 80.98,
//           breakFast: true,
//           refund: false,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//         {
//           id: 303,
//           title: "Standard Single Bed, Only Single",
//           fitForAdults: 3,
//           fitForChildren: 0,
//           price: 50.98,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//         {
//           id: 304,
//           title: "Presidential Suite Double Only",
//           fitForAdults: 4,
//           fitForChildren: 0,
//           price: 13.98,
//           breakFast: false,
//           refund: false,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },

//         {
//           id: 305,
//           title: "Double Bed Room x 3 Twins Bed",
//           fitForAdults: 2,
//           fitForChildren: 3,
//           price: 10.98,
//           breakFast: false,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "70 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },

//         {
//           id: 306,
//           title: "Double Bed Room x 3 Twins Bed",
//           fitForAdults: 2,
//           fitForChildren: 3,
//           price: 300.98,
//           breakFast: false,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "70 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//       ],
//     },
//   ],
// };

export const hotelsData = {
  Bahrain: [
    {
      id: 1,
      position: { lat: 26.2708, lon: 50.6261 },
      name: "Sheraton Bahrain Hotel",
      location: "6 Palace Avenue, Manama",
      price: 120,
      image: "https://images.trvl-media.com/lodging/1000000/20000/17700/17686/832e6431.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      rating: 5,
      description:
        "Sheraton Bahrain Hotel offers luxury accommodation in the heart of Manama, close to shopping malls and cultural attractions.",
      facilities: ["Free WiFi", "Pool", "Spa", "Gym", "Restaurant"],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],
      rooms: [
        {
          id: 1001,
          title: "Deluxe Room",
          fitForAdults: 2,
          fitForChildren: 1,
          roomPhotos: [
            "https://images.unsplash.com/photo-1582473788025-c058a699e488?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGhvdGVsJTIwcm9vbSUyMG9jZWFufGVufDB8fDB8fHww",
            "https://plus.unsplash.com/premium_photo-1663126637580-ff22a73f9bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1619110457577-316b0a7457e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 1,
            size: "30m²",
            amenities: ["Free WiFi", "Flat-screen TV", "Mini Bar", "City View"],
          },
          variations: [
            {
              type: "Room Only",
              price: 120,
              oldprice: 150,
              off: "20%",
              mealPlan: "Room Only",
              breakfast: false,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            // {
            //   type: "Bed & Breakfast",
            //   price: 140,
            //   oldprice: 170,
            //   off: "18%",
            //   mealPlan: "Bed and Breakfast",
            //   breakfast: true,
            //   lunch: false,
            //   dinner: false,
            //   refund: true,
            //   cancellation: true,
            // },
            {
              type: "Half Board",
              price: 170,
              oldprice: 200,
              off: "15%",
              mealPlan: "Half Board",
              breakfast: true,
              lunch: true,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Full Board",
              price: 200,
              oldprice: 240,
              off: "17%",
              mealPlan: "Full Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
          ],
        },
        {
          id: 1002,
          title: "Executive Suite",
          fitForAdults: 2,
          fitForChildren: 2,
          roomPhotos: [
            "https://images.unsplash.com/photo-1582473788025-c058a699e488?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGhvdGVsJTIwcm9vbSUyMG9jZWFufGVufDB8fDB8fHww",
            "https://plus.unsplash.com/premium_photo-1663126637580-ff22a73f9bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1619110457577-316b0a7457e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 1,
            size: "50m²",
            amenities: [
              "Free WiFi",
              "King Bed",
              "Jacuzzi",
              "Balcony with Sea View",
            ],
          },
          variations: [
            {
              type: "Room Only",
              price: 220,
              oldprice: 270,
              off: "19%",
              mealPlan: "Room Only",
              breakfast: false,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Bed & Breakfast",
              price: 250,
              oldprice: 300,
              off: "17%",
              mealPlan: "Bed and Breakfast",
              breakfast: true,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Half Board",
              price: 280,
              oldprice: 330,
              off: "15%",
              mealPlan: "Half Board",
              breakfast: true,
              lunch: true,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Full Board",
              price: 320,
              oldprice: 380,
              off: "16%",
              mealPlan: "Full Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
          ],
        },
      ],
    },
    {
      id: 2,
      position: { lat: 26.2361, lon: 50.5831 },
      name: "Jumeirah Gulf of Bahrain",
      location: "Zallaq, Manama",
      price: 150,
      image:
        "https://images.trvl-media.com/lodging/77000000/76880000/76870300/76870281/eda22e09.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      rating: 5,
      description:
        "Jumeirah Gulf of Bahrain Resort offers premium beachfront luxury with outstanding dining, spa, and leisure facilities.",
      facilities: ["Private Beach", "Spa", "Gym", "Restaurants", "Kids Club"],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],
      rooms: [
        {
          id: 2001,
          title: "Ocean View Room",
          fitForAdults: 2,
          fitForChildren: 1,
          roomPhotos: [
            "https://images.unsplash.com/photo-1582473788025-c058a699e488?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGhvdGVsJTIwcm9vbSUyMG9jZWFufGVufDB8fDB8fHww",
            "https://plus.unsplash.com/premium_photo-1663126637580-ff22a73f9bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1619110457577-316b0a7457e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 1,
            size: "35m²",
            amenities: ["Free WiFi", "Flat-screen TV", "Balcony", "Sea View"],
          },
          variations: [
            {
              type: "Room Only",
              price: 180,
              oldprice: 220,
              off: "18%",
              mealPlan: "Room Only",
              breakfast: false,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Bed & Breakfast",
              price: 210,
              oldprice: 250,
              off: "16%",
              mealPlan: "Bed and Breakfast",
              breakfast: true,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Half Board",
              price: 250,
              oldprice: 290,
              off: "14%",
              mealPlan: "Half Board",
              breakfast: true,
              lunch: true,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Full Board",
              price: 300,
              oldprice: 360,
              off: "17%",
              mealPlan: "Full Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
          ],
        },
        {
          id: 2002,
          title: "Royal Suite",
          fitForAdults: 2,
          fitForChildren: 2,
          roomPhotos: [
            "https://plus.unsplash.com/premium_photo-1661962688308-2b00b88b9765?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://plus.unsplash.com/premium_photo-1663126637580-ff22a73f9bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1619110457577-316b0a7457e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 1,
            size: "80m²",
            amenities: [
              "Private Pool",
              "Luxury King Bed",
              "Personal Butler",
              "Sea View",
            ],
          },
          variations: [
            {
              type: "Room Only",
              price: 400,
              oldprice: 480,
              off: "17%",
              mealPlan: "Room Only",
              breakfast: false,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Bed & Breakfast",
              price: 450,
              oldprice: 540,
              off: "17%",
              mealPlan: "Bed and Breakfast",
              breakfast: true,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Half Board",
              price: 520,
              oldprice: 600,
              off: "13%",
              mealPlan: "Half Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
            {
              type: "Full Board",
              price: 600,
              oldprice: 700,
              off: "14%",
              mealPlan: "Full Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
          ],
        },
      ],
    },
  ],

  Dubai: [
    {
      id: 3,
      position: { lat: 25.2048, lon: 55.2708 },
      name: "Burj Al Arab Jumeirah",
      location: "Jumeirah St, Dubai",
      price: 400,
      image:
        "https://cf.bstatic.com/xdata/images/hotel/square600/347666974.webp?k=7720fdb6cefe4845c347ef31dc6808ebfabf7c3e34589dc540a17d86489887fb&o=",
      rating: 5,
      description:
        "The iconic Burj Al Arab Jumeirah offers unparalleled luxury, breathtaking views of the Arabian Gulf, and world-class dining.",
      facilities: ["Private Beach", "Helipad", "Spa", "Gym", "Multiple Restaurants"],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],
      rooms: [
        {
          id: 3001,
          title: "Panoramic Suite",
          fitForAdults: 2,
          fitForChildren: 2,
          roomPhotos: [
            "https://plus.unsplash.com/premium_photo-1661962688308-2b00b88b9765?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://plus.unsplash.com/premium_photo-1663126637580-ff22a73f9bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1619110457577-316b0a7457e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 1,
            size: "50m²",
            amenities: ["Free WiFi", "Panoramic View", "Luxury Bathroom", "Smart Home System"],
          },
          variations: [
            {
              type: "Room Only",
              price: 500,
              oldprice: 600,
              off: "17%",
              mealPlan: "Room Only",
              breakfast: false,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Bed & Breakfast",
              price: 550,
              oldprice: 650,
              off: "15%",
              mealPlan: "Bed and Breakfast",
              breakfast: true,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Half Board",
              price: 620,
              oldprice: 720,
              off: "14%",
              mealPlan: "Half Board",
              breakfast: true,
              lunch: true,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Full Board",
              price: 700,
              oldprice: 820,
              off: "15%",
              mealPlan: "Full Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
          ],
        },
        {
          id: 3002,
          title: "Royal Suite",
          fitForAdults: 2,
          fitForChildren: 2,
          roomPhotos: [
            "https://images.unsplash.com/photo-1672122816795-49ff5cbc75e8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "120m²",
            amenities: [
              "Private Butler",
              "Jacuzzi",
              "Private Elevator",
              "Sea View Balcony",
            ],
          },
          variations: [
            {
              type: "Room Only",
              price: 1200,
              oldprice: 1400,
              off: "14%",
              mealPlan: "Room Only",
              breakfast: false,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Bed & Breakfast",
              price: 1300,
              oldprice: 1500,
              off: "13%",
              mealPlan: "Bed and Breakfast",
              breakfast: true,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Half Board",
              price: 1500,
              oldprice: 1700,
              off: "12%",
              mealPlan: "Half Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
            {
              type: "Full Board",
              price: 1700,
              oldprice: 1950,
              off: "13%",
              mealPlan: "Full Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
          ],
        },
      ],
    },
    {
      id: 4,
      position: { lat: 25.1972, lon: 55.2744 },
      name: "Atlantis The Palm",
      location: "Crescent Rd, The Palm Jumeirah, Dubai",
      price: 300,
      image:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGhvdGVsfGVufDB8fDB8fHww",
      rating: 5,
      description:
        "Atlantis The Palm is a majestic ocean-themed resort featuring an underwater aquarium, waterpark, and luxury accommodation.",
      facilities: ["Aquarium", "Waterpark", "Spa", "Restaurants", "Private Beach"],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],
      rooms: [
        {
          id: 4001,
          title: "Ocean Deluxe Room",
          fitForAdults: 2,
          fitForChildren: 2,
          roomPhotos: [
            "https://images.unsplash.com/photo-1661258412259-fe5a585c1450?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTA0fHxob3RlbCUyMHJvb20lMjBpbWFnZXN8ZW58MHx8MHx8fDA%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "45m²",
            amenities: ["Free WiFi", "Balcony", "Mini Bar", "Ocean View"],
          },
          variations: [
            {
              type: "Room Only",
              price: 350,
              oldprice: 420,
              off: "16%",
              mealPlan: "Room Only",
              breakfast: false,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Bed & Breakfast",
              price: 400,
              oldprice: 470,
              off: "15%",
              mealPlan: "Bed and Breakfast",
              breakfast: true,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Half Board",
              price: 480,
              oldprice: 560,
              off: "14%",
              mealPlan: "Half Board",
              breakfast: true,
              lunch: true,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Full Board",
              price: 550,
              oldprice: 650,
              off: "15%",
              mealPlan: "Full Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
          ],
        },
        {
          id: 4002,
          title: "Underwater Suite",
          fitForAdults: 2,
          fitForChildren: 1,
          roomPhotos: [
            "https://images.unsplash.com/photo-1743273291499-e2c1da988688?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTV8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "165m²",
            amenities: ["Underwater View", "Luxury Bathroom", "24/7 Butler", "Jacuzzi"],
          },
          variations: [
            {
              type: "Room Only",
              price: 800,
              oldprice: 950,
              off: "16%",
              mealPlan: "Room Only",
              breakfast: false,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Bed & Breakfast",
              price: 880,
              oldprice: 1050,
              off: "16%",
              mealPlan: "Bed and Breakfast",
              breakfast: true,
              lunch: false,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Half Board",
              price: 1000,
              oldprice: 1200,
              off: "17%",
              mealPlan: "Half Board",
              breakfast: true,
              lunch: true,
              dinner: false,
              refund: true,
              cancellation: true,
            },
            {
              type: "Full Board",
              price: 1200,
              oldprice: 1450,
              off: "17%",
              mealPlan: "Full Board",
              breakfast: true,
              lunch: true,
              dinner: true,
              refund: true,
              cancellation: true,
            },
          ],
        },
      ],
    },
  ],
};

