export const hotelsData = {
  Bahrain: [
    {
      id: 1,
      name: "Islamabad Serena Hotel",
      location: "Khaliq Uz Zaman Road, Islamabad",
      price: 120,
      image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
      rating: 5,
      description:
        "Islamabad Serena Hotel is a commercial establishment that provides lodging, meals, and other services to guests, travelers, and tourists.",
      facilities: [
        "Restaurant & Bar",
        "Airport Shuttle",
        "Conference Hall",
        "Laundry Service",
        "Car Rental",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
        "https://static.cupid.travel/hotels/518526053.jpg",
        "https://static.cupid.travel/hotels/491810902.jpg",
        "https://static.cupid.travel/hotels/491176899.jpg",
      ],
      rooms: [
        {
          id: 101,
          title: "1 x Deluxe Double Room, 1 Double Bed, Smoking",
          fitForAdults: 2,
          fitForChildren: 1,
          price: 120.68,
          breakFast:true,
          refund:true,
          off:8,
          oldprice:60,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 5,
            size: "25 m²",
            amenities: ["Minibar", "Shower", "Safety deposit box", "TV"],
          },
        },
        {
          id: 102,
          title: "Executive Suite",
          fitForAdults: 3,
          fitForChildren: 2,
          price: 180.99,
          breakFast:false,
          refund:false,
          off:8,
          oldprice:90,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 3,
            size: "40 m²",
            amenities: ["Jacuzzi", "Balcony", "Flat-screen TV", "Work Desk"],
          },
        },
      ],
    },
    {
      id: 2,
      name: "Marriott Hotel, Islamabad",
      location: "Agha Khan Road, Islamabad",
      price: 90,
      image:
        "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=600&auto=format&fit=crop&q=60",
      rating: 4,
      description:
        "Marriott Hotel, Islamabad is a commercial establishment that provides lodging, meals, and other services.",
      facilities: [
        "Free Wi-Fi",
        "24/7 Room Service",
        "Swimming Pool",
        "Fitness Center",
        "Spa & Wellness",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/518527047.jpg",
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518526053.jpg",
      ],
      rooms: [
        {
          id: 201,
          title: "Standard Room",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 90.50,
          breakFast:true,
          refund:true,
          off:8,
          oldprice:50,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 10,
            size: "20 m²",
            amenities: ["Wi-Fi", "TV", "Private Bathroom"],
          },
        },
        {
          id: 202,
          title: "Luxury Suite",
          fitForAdults: 4,
          fitForChildren: 2,
          price: 150.70,
          breakFast:true,
          refund:true,
          off:8,
          oldprice:360,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 2,
            size: "60 m²",
            amenities: ["Kitchenette", "Balcony", "Living Area", "Jacuzzi"],
          },
        },
      ],
    },
  ],

  Dubai: [
    {
      id: 1,
      name: "Pearl Continental Lahore",
      location: "Shahrah-e-Quaid-e-Azam, Lahore",
      price: 150,
      image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
      rating: 2,
      description:
        "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
      facilities: [
        "Business Center",
        "Concierge Service",
        "Mini Bar in Rooms",
        "Luggage Storage",
        "Daily Housekeeping",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],
      rooms: [
        {
          id: 301,
          title: "Classic Room",
          fitForAdults: 2,
          fitForChildren: 1,
          price: 150.99,
          breakFast:true,
          refund:true,
          off:8,
          oldprice:80,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 8,
            size: "22 m²",
            amenities: ["AC", "TV", "Private Bathroom"],
          },
        },
        {
          id: 302,
          title: "Presidential Suite",
          fitForAdults: 4,
          fitForChildren: 3,
          price: 300.99,
           breakFast:true,
          refund:true,
          off:8,
          oldprice:40,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
      ],
    },

    {
      id: 2,
      name: "Pearl Continental Lahore",
      location: "Shahrah-e-Quaid-e-Azam, Lahore",
      price: 150.99,
      image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
      rating: 2,
      description:
        "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
      facilities: [
        "Business Center",
        "Concierge Service",
        "Mini Bar in Rooms",
        "Luggage Storage",
        "Daily Housekeeping",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],
      rooms: [
        // {
        //   id: 301,
        //   title: "Classic Room",
        //   fitForAdults: 2,
        //   fitForChildren: 1,
        //   price: 150,
        //   roomDetails: {
        //     count: 8,
        //     size: "22 m²",
        //     amenities: ["AC", "TV", "Private Bathroom"],
        //   },
        // },
        {
          id: 302,
          title: "Presidential Suite",
          fitForAdults: 4,
          fitForChildren: 3,
          price: 300.98,
          breakFast:true,
          refund:false,
          off:8,
          oldprice:60,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
        {
          id: 303,
          title: "Presidential Suite",
          fitForAdults: 4,
          fitForChildren: 3,
          price: 300.98,
          breakFast:true,
          refund:false,
          off:8,
          oldprice:60,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
        {
          id: 304,
          title: "Presidential Suite",
          fitForAdults: 10,
          fitForChildren: 2,
          price: 1300.98,
          breakFast:true,
          refund:false,
          off:8,
          oldprice:60,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },

        {
          id: 305,
          title: "Presidential Suite",
          fitForAdults: 12,
          fitForChildren: 3,
          price: 1300.98,
          breakFast:true,
          refund:false,
          off:8,
          oldprice:60,
          roomPhotos:["https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg"
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
      ],
    },
  ],
};
