// export const hotelsData = {
//   Bahrain: [
//     {
//       id: 1,
//       position: [26.2708, 50.6261],
//       name: "Islamabad Serena Hotel",
//       location: "Khaliq Uz Zaman Road, Islamabad",
//       price: 120,
//       image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
//       rating: 5,
//       description:
//         "Islamabad Serena Hotel is a commercial establishment that provides lodging, meals, and other services to guests, travelers, and tourists.",
//       facilities: [
//         "Restaurant & Bar",
//         "Airport Shuttle",
//         "Conference Hall",
//         "Laundry Service",
//         "Car Rental",
//       ],
//       roomImages: [
//         "https://static.cupid.travel/hotels/508614426.jpg",
//         "https://static.cupid.travel/hotels/518527047.jpg",
//         "https://static.cupid.travel/hotels/518526053.jpg",
//         "https://static.cupid.travel/hotels/491810902.jpg",
//         "https://static.cupid.travel/hotels/491176899.jpg",
//       ],
//       rooms: [
//         {
//           id: 101,
//           title: "1 x Deluxe Double Room, 1 Double Bed, Smoking",
//           fitForAdults: 2,
//           fitForChildren: 1,
//           price: 120.68,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 5,
//             size: "25 m²",
//             amenities: ["Minibar", "Shower", "Safety deposit box", "TV"],
//           },
//         },
//         {
//           id: 102,
//           title: "Executive Suite",
//           fitForAdults: 3,
//           fitForChildren: 2,
//           price: 180.99,
//           breakFast: false,
//           refund: false,
//           off: 8,
//           Cancelation: true,
//           oldprice: 90,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 3,
//             size: "40 m²",
//             amenities: ["Jacuzzi", "Balcony", "Flat-screen TV", "Work Desk"],
//           },
//         },
//       ],
//     },
//     {
//       id: 2,
//       position: [19.2708, 50.6261],
//       name: "Marriott Hotel, Islamabad",
//       location: "Agha Khan Road, Islamabad",
//       price: 90,
//       image:
//         "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?w=600&auto=format&fit=crop&q=60",
//       rating: 4,
//       description:
//         "Marriott Hotel, Islamabad is a commercial establishment that provides lodging, meals, and other services.",
//       facilities: [
//         "Free Wi-Fi",
//         "24/7 Room Service",
//         "Swimming Pool",
//         "Fitness Center",
//         "Spa & Wellness",
//       ],
//       roomImages: [
//         "https://static.cupid.travel/hotels/518527047.jpg",
//         "https://static.cupid.travel/hotels/508614426.jpg",
//         "https://static.cupid.travel/hotels/518526053.jpg",
//       ],
//       rooms: [
//         {
//           id: 201,
//           title: "Standard Room",
//           fitForAdults: 2,
//           fitForChildren: 0,
//           price: 90.5,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 50,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 10,
//             size: "20 m²",
//             amenities: ["Wi-Fi", "TV", "Private Bathroom"],
//           },
//         },
//         {
//           id: 202,
//           title: "Luxury Suite",
//           fitForAdults: 4,
//           fitForChildren: 2,
//           price: 150.7,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 360,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 2,
//             size: "60 m²",
//             amenities: ["Kitchenette", "Balcony", "Living Area", "Jacuzzi"],
//           },
//         },
//       ],
//     },
//   ],

//   Dubai: [
//     {
//       id: 1,
//       position: [26.1292, 50.555],
//       name: "Pearl Continental Lahore",
//       location: "Shahrah-e-Quaid-e-Azam, Lahore",
//       price: 50,
//       image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
//       rating: 2,
//       description:
//         "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
//       facilities: [
//         "Business Center",
//         "Concierge Service",
//         "Mini Bar in Rooms",
//         "Luggage Storage",
//         "Daily Housekeeping",
//       ],
//       roomImages: [
//         "https://static.cupid.travel/hotels/508614426.jpg",
//         "https://static.cupid.travel/hotels/518527047.jpg",
//       ],
//       rooms: [
//         {
//           id: 301,
//           title: "Classic Room",
//           fitForAdults: 2,
//           fitForChildren: 1,
//           price: 150.99,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 80,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 8,
//             size: "22 m²",
//             amenities: ["AC", "TV", "Private Bathroom"],
//           },
//         },
//         {
//           id: 302,
//           title: "Presidential Suite",
//           fitForAdults: 4,
//           fitForChildren: 3,
//           price: 50.99,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 40,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//         {
//           id: 303,
//           title: "Presidential Suite",
//           fitForAdults: 1,
//           fitForChildren: 0,
//           price: 80.99,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: false,
//           oldprice: 40,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//       ],
//     },

//     {
//       id: 2,
//       position: [28.1292, 52.555],
//       name: "Pearl Continental Lahore",
//       location: "Shahrah-e-Quaid-e-Azam, Lahore",
//       price: 10.99,
//       image: "https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg",
//       rating: 2,
//       description:
//         "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
//       facilities: [
//         "Business Center",
//         "Concierge Service",
//         "Mini Bar in Rooms",
//         "Luggage Storage",
//         "Daily Housekeeping",
//       ],
//       roomImages: [
//         "https://static.cupid.travel/hotels/508614426.jpg",
//         "https://static.cupid.travel/hotels/518527047.jpg",
//       ],
//       rooms: [
//         // {
//         //   id: 301,
//         //   title: "Classic Room",
//         //   fitForAdults: 2,
//         //   fitForChildren: 1,
//         //   price: 150,
//         //   roomDetails: {
//         //     count: 8,
//         //     size: "22 m²",
//         //     amenities: ["AC", "TV", "Private Bathroom"],
//         //   },
//         // },
//         {
//           id: 302,
//           title: "Presidential Suite",
//           fitForAdults: 2,
//           fitForChildren: 3,
//           price: 80.98,
//           breakFast: true,
//           refund: false,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//         {
//           id: 303,
//           title: "Standard Single Bed, Only Single",
//           fitForAdults: 3,
//           fitForChildren: 0,
//           price: 50.98,
//           breakFast: true,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//         {
//           id: 304,
//           title: "Presidential Suite Double Only",
//           fitForAdults: 4,
//           fitForChildren: 0,
//           price: 13.98,
//           breakFast: false,
//           refund: false,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "80 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },

//         {
//           id: 305,
//           title: "Double Bed Room x 3 Twins Bed",
//           fitForAdults: 2,
//           fitForChildren: 3,
//           price: 10.98,
//           breakFast: false,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "70 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },

//         {
//           id: 306,
//           title: "Double Bed Room x 3 Twins Bed",
//           fitForAdults: 2,
//           fitForChildren: 3,
//           price: 300.98,
//           breakFast: false,
//           refund: true,
//           off: 8,
//           Cancelation: true,
//           oldprice: 60,
//           roomPhotos: [
//             "https://static.cupid.travel/rooms-large-pictures/ex_w1021h765x0y0-7875366c_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
//             "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
//           ],
//           roomDetails: {
//             count: 1,
//             size: "70 m²",
//             amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
//           },
//         },
//       ],
//     },
//   ],
// };

export const hotelsData = {
  Bahrain: [
    {
      id: 1,
      position: { lat: 26.23923244305487, lon: 50.58326163741393 }, // ✅ updated
      name: "Sheraton Bahrain Hotel, Bahrain",
      location: "6 Palace Avenue, Manama",
      price: 20.99,
      image: "https://images.trvl-media.com/lodging/1000000/20000/17700/17686/832e6431.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      rating: 5,
      description:
        "Islamabad Serena Hotel is a commercial establishment that provides lodging, meals, and other services to guests, travelers, and tourists.",
      facilities: [
        "Restaurant & Bar",
        "Airport Shuttle",
        "Conference Hall",
        "Laundry Service",
        "Car Rental",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
        "https://static.cupid.travel/hotels/518526053.jpg",
        "https://static.cupid.travel/hotels/491810902.jpg",
        "https://static.cupid.travel/hotels/491176899.jpg",
      ],
       rooms: [
        {
          id: 301,
          title: "Club Room, 1 Double Bed",
          fitForAdults: 2,
          fitForChildren: 1,
          price: 45.99,
          breakFast: false,
          refund: true,
          mealPlan: "Room Only",
          off: 3,
          Cancelation: false,
          oldprice: 80,
          roomPhotos: [
            "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww",
            "https://plus.unsplash.com/premium_photo-1663126637580-ff22a73f9bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1619110457577-316b0a7457e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 8,
            size: "22 m²",
            amenities: ["AC", "TV", "Private Bathroom"],
          },
        },
        {
          id: 302,
          title: "Junior Suite, 1 King Bed",
          fitForAdults: 2,
          fitForChildren: 3,
          price: 140.99,
          breakFast: true,
          refund: false,
          mealPlan: "Bed and Breakfast",
          off: 8,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://plus.unsplash.com/premium_photo-1675616563084-63d1f129623d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1723729544758-dd3142bc7df5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://images.unsplash.com/photo-1648383228240-6ed939727ad6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
        {
          id: 303,
          title: "Signature Room, 1 King Bed, Non Smoking, City View",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 350.99,
          mealPlan: "Full Board",
          breakFast: true,
          refund: true,
          off: 8,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },

        {
          id: 304,
          title: "Presidential Suite, 1 King Bed, Non Smoking",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 270.99,
          mealPlan: "Half Board",
          breakFast: true,
          refund: true,
          off: 8,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://plus.unsplash.com/premium_photo-1661879252375-7c1db1932572?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
      ],
    },
    {

      id: 2,
      position: { lat: 25.927009706369795, lon: 50.49222539321749 }, // ✅ updated
      name: "Jumeirah Gulf of Bahrain",
      location: "Building 278 Road 63 Block 1067, Zallaq, Zallaq",
      price: 50,
      image:
        "https://images.trvl-media.com/lodging/77000000/76880000/76870300/76870281/eda22e09.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      rating: 5,
      description:
        "Marriott Hotel, Islamabad is a commercial establishment that provides lodging, meals, and other services.",
      facilities: [
        "Free Wi-Fi",
        "24/7 Room Service",
        "Swimming Pool",
        "Fitness Center",
        "Spa & Wellness",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/518527047.jpg",
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518526053.jpg",
      ],
       rooms: [
        {
          id: 301,
          title: "Suite, Terrace (Ocean)",
          fitForAdults: 2,
          fitForChildren: 1,
          price: 70.99,
          breakFast: false,
          refund: true,
          mealPlan: "Room Only",
          off: 6,
          Cancelation: false,
          oldprice: 80,
          roomPhotos: [
            "https://images.unsplash.com/photo-1582473788025-c058a699e488?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGhvdGVsJTIwcm9vbSUyMG9jZWFufGVufDB8fDB8fHww",
            "https://plus.unsplash.com/premium_photo-1663126637580-ff22a73f9bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1619110457577-316b0a7457e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 8,
            size: "22 m²",
            amenities: ["AC", "TV", "Private Bathroom"],
          },
        },
        {
          id: 302,
          title: "Junior Suite, 1 King Bed",
          fitForAdults: 2,
          fitForChildren: 3,
          price: 100.99,
          breakFast: true,
          refund: false,
          mealPlan: "Bed and Breakfast",
          off: 10,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
            "https://images.unsplash.com/photo-1723729544758-dd3142bc7df5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://images.unsplash.com/photo-1648383228240-6ed939727ad6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
        {
          id: 303,
          title: "Executive Suite, 1 King Bed",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 320.99,
          mealPlan: "Full Board",
          breakFast: true,
          refund: true,
          off: 8,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://plus.unsplash.com/premium_photo-1674676471380-1258cb31b3ac?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },

        {
          id: 304,
          title: "Presidential Suite, 1 King Bed, Non Smoking",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 220.99,
          mealPlan: "Half Board",
          breakFast: true,
          refund: true,
          off: 8,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://images.unsplash.com/photo-1587985064135-0366536eab42?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDB8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
      ],
    },
  ],

  Dubai: [
    {
      id: 1,
      position: { lat: 25.244709690096606, lon: 55.29870230158505 }, // ✅ updated
      name: "President Hotel, Dubai",
      location: "Al Karama, Dubai (Bur Dubai)",
      price: 50,
      image: "https://cf.bstatic.com/xdata/images/hotel/square240/473478912.webp?k=b9ec4d0ff00b3123c910ec53d4e65c80a0d0cdf8e50427618c86de8b8e20c1cb&o=",
      rating: 2,
      description:
        "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
      facilities: [
        "Business Center",
        "Concierge Service",
        "Mini Bar in Rooms",
        "Luggage Storage",
        "Daily Housekeeping",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],
      rooms: [
        {
          id: 301,
          title: "Classic Room",
          fitForAdults: 2,
          fitForChildren: 1,
          price: 20.99,
          breakFast: false,
          refund: true,
          mealPlan: "Room Only",
          off: 8,
          Cancelation: true,
          oldprice: 80,
          roomPhotos: [
            "https://plus.unsplash.com/premium_photo-1661962688308-2b00b88b9765?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://plus.unsplash.com/premium_photo-1663126637580-ff22a73f9bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8aG90ZWwlMjByb29tJTIwaW1hZ2VzfGVufDB8fDB8fHww",
            "https://images.unsplash.com/photo-1619110457577-316b0a7457e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 8,
            size: "22 m²",
            amenities: ["AC", "TV", "Private Bathroom"],
          },
        },
        {
          id: 302,
          title: "Standard Queen Room",
          fitForAdults: 2,
          fitForChildren: 3,
          price: 140.99,
          breakFast: true,
          refund: false,
          mealPlan: "Bed and Breakfast",
          off: 8,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://images.unsplash.com/photo-1601003243101-806fe77dd4b4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://images.unsplash.com/photo-1723729544758-dd3142bc7df5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://images.unsplash.com/photo-1648383228240-6ed939727ad6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
        {
          id: 303,
          title: "Presidential Suite",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 200.99,
          mealPlan: "Full Board",
          breakFast: true,
          refund: true,
          off: 8,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://images.unsplash.com/photo-1648383228240-6ed939727ad6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },

        {
          id: 304,
          title: "Junior Suite",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 160.99,
          mealPlan: "Half Board",
          breakFast: true,
          refund: true,
          off: 8,
          Cancelation: true,
          oldprice: 40,
          roomPhotos: [
            "https://images.unsplash.com/photo-1610456219577-88d991c46bfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
      ],
    },
    {
      id: 2,
      position: { lat: 25.25934231634163, lon: 55.28748350777487 }, // ✅ updated
      name: "Palm Beach Hotel, Dubai",
      location: "Beach & Coast, Dubai (Bur Dubai)",
      price: 19.99,
      image: "https://cf.bstatic.com/xdata/images/hotel/square600/347666974.webp?k=7720fdb6cefe4845c347ef31dc6808ebfabf7c3e34589dc540a17d86489887fb&o=",
      rating: 4,
      description:
        "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
      facilities: [
        "Business Center",
        "Concierge Service",
        "Mini Bar in Rooms",
        "Luggage Storage",
        "Daily Housekeeping",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],

      
      rooms: [
        {
          id: 302,
          title: "Standard Queen Room",
          fitForAdults: 2,
          fitForChildren: 3,
          price: 60.98,
          breakFast: false,
          refund: false,
          mealPlan: "Room Only",
          off: 8,
          Cancelation: true,
          oldprice: 60,
          roomPhotos: [
            "https://images.unsplash.com/photo-1658326361076-6bd11b39956a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjN8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
        {
          id: 303,
          title: "Standard Single Bed, Only Single",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 99.98,
          breakFast: true,
           mealPlan: "Bed and Breakfast",
          refund: true,
          off: 8,
          Cancelation: true,
          oldprice: 60,
          roomPhotos: [
            "https://images.unsplash.com/photo-1621891337421-af0e6b355e2f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDh8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },

        {
          id: 304,
          title: "Standard Single Bed, Only Single",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 120.98,
          breakFast: true,
          refund: true,
          mealPlan: "Full Board",
          off: 8,
          Cancelation: true,
          oldprice: 60,
          roomPhotos: [
            "https://images.unsplash.com/photo-1664227430717-9a62112984cf?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
      ],
    },

    {
      id: 3,
      position: { lat: 25.259200213916348, lon: 55.289010293179956 }, // ✅ updated
      name: "City Palace Hotel, Dubai",
      location: "Beach & Coast, Dubai (Bur Dubai)",
      price: 10.99,
      image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGhvdGVsfGVufDB8fDB8fHww",
      rating: 3,
      description:
        "Pearl Continental Lahore is a commercial establishment that provides lodging, meals, and other services.",
      facilities: [
        "Business Center",
        "Concierge Service",
        "Mini Bar in Rooms",
        "Luggage Storage",
        "Daily Housekeeping",
      ],
      roomImages: [
        "https://static.cupid.travel/hotels/508614426.jpg",
        "https://static.cupid.travel/hotels/518527047.jpg",
      ],
      rooms: [
        {
          id: 302,
          title: "Presidential Suite",
          fitForAdults: 2,
          fitForChildren: 3,
          price: 50.98,
          breakFast: false,
          refund: false,
          mealPlan: "Room Only",
          off: 8,
          Cancelation: true,
          oldprice: 60,
          roomPhotos: [
            "https://images.unsplash.com/photo-1626868449668-fb47a048d9cb?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
        {
          id: 303,
          title: "Standard Single Bed, Only Single",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 67.98,
          breakFast: true,
          refund: true,
          mealPlan: "Bed and Breakfast",
          off: 8,
          Cancelation: true,
          oldprice: 60,
          roomPhotos: [
            "https://images.unsplash.com/photo-1672122816795-49ff5cbc75e8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTR8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },

        {
          id: 304,
          title: "Duelx Twin Rooms",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 200.98,
          breakFast: true,
          refund: true,
          mealPlan: "Full Board",
          off: 8,
          Cancelation: true,
          oldprice: 60,
          roomPhotos: [
            "https://images.unsplash.com/photo-1630999295881-e00725e1de45?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTI3fHxob3RlbCUyMHJvb20lMjBpbWFnZXN8ZW58MHx8MHx8fDA%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },

         {
          id: 305,
          title: "2 Duelx Twin Rooms",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 150.98,
          breakFast: true,
          refund: true,
          mealPlan: "Half Board",
          off: 8,
          Cancelation: true,
          oldprice: 60,
          roomPhotos: [
            "https://images.unsplash.com/photo-1661258412259-fe5a585c1450?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTA0fHxob3RlbCUyMHJvb20lMjBpbWFnZXN8ZW58MHx8MHx8fDA%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },

         {
          id: 306,
          title: "Royal Suite x 2",
          fitForAdults: 2,
          fitForChildren: 0,
          price: 240.98,
          breakFast: true,
          refund: true,
          mealPlan: "Full Board",
          off: 4,
          Cancelation: true,
          oldprice: 60,
          roomPhotos: [
            "https://images.unsplash.com/photo-1743273291499-e2c1da988688?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTV8fGhvdGVsJTIwcm9vbSUyMGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D",
            "https://static.cupid.travel/rooms-large-pictures/ex_046d1ff8_z.jpg",
            "https://static.cupid.travel/rooms-large-pictures/ex_1f5ec217_z.jpg",
          ],
          roomDetails: {
            count: 1,
            size: "80 m²",
            amenities: ["Jacuzzi", "Private Bar", "Kitchen", "Luxury Seating"],
          },
        },
      ],
    },
  ],
};

