const countryCodes = [

  { code: "+1", name: "Usa / Ca", iso: "us" },
  { code: "+7", name: "Russia / Kazakhstan", iso: "ru" },
  { code: "+20", name: "Egypt", iso: "eg" },
  { code: "+27", name: "South Africa", iso: "za" },
  { code: "+30", name: "Greece", iso: "gr" },
  { code: "+31", name: "Netherlands", iso: "nl" },
  { code: "+32", name: "Belgium", iso: "be" },
  { code: "+33", name: "France", iso: "fr" },
  { code: "+34", name: "Spain", iso: "es" },
  { code: "+36", name: "Hungary", iso: "hu" },
  { code: "+39", name: "Italy", iso: "it" },
  { code: "+40", name: "Romania", iso: "ro" },
  { code: "+41", name: "Switzerland", iso: "ch" },
  { code: "+43", name: "Austria", iso: "at" },
  { code: "+44", name: "United Kingdom", iso: "gb" },
  { code: "+45", name: "Denmark", iso: "dk" },
  { code: "+46", name: "Sweden", iso: "se" },
  { code: "+47", name: "Norway", iso: "no" },
  { code: "+48", name: "Poland", iso: "pl" },
  { code: "+49", name: "Germany", iso: "de" },
  { code: "+51", name: "Peru", iso: "pe" },
  { code: "+52", name: "Mexico", iso: "mx" },
  { code: "+53", name: "Cuba", iso: "cu" },
  { code: "+54", name: "Argentina", iso: "ar" },
  { code: "+55", name: "Brazil", iso: "br" },
  { code: "+56", name: "Chile", iso: "cl" },
  { code: "+57", name: "Colombia", iso: "co" },
  { code: "+58", name: "Venezuela", iso: "ve" },
  { code: "+60", name: "Malaysia", iso: "my" },
  { code: "+61", name: "Australia", iso: "au" },
  { code: "+62", name: "Indonesia", iso: "id" },
  { code: "+63", name: "Philippines", iso: "ph" },
  { code: "+64", name: "New Zealand", iso: "nz" },
  { code: "+65", name: "Singapore", iso: "sg" },
  { code: "+66", name: "Thailand", iso: "th" },
  { code: "+81", name: "Japan", iso: "jp" },
  { code: "+82", name: "South Korea", iso: "kr" },
  { code: "+84", name: "Vietnam", iso: "vn" },
  { code: "+86", name: "China", iso: "cn" },
  { code: "+90", name: "Turkey", iso: "tr" },
  { code: "+91", name: "India", iso: "in" },
  { code: "+92", name: "Pakistan", iso: "pk" },
  { code: "+93", name: "Afghanistan", iso: "af" },
  { code: "+94", name: "Sri Lanka", iso: "lk" },
  { code: "+95", name: "Myanmar", iso: "mm" },
  { code: "+98", name: "Iran", iso: "ir" },
  { code: "+211", name: "South Sudan", iso: "ss" },
  { code: "+212", name: "Morocco", iso: "ma" },
  { code: "+213", name: "Algeria", iso: "dz" },
  { code: "+216", name: "Tunisia", iso: "tn" },
  { code: "+218", name: "Libya", iso: "ly" },
  { code: "+220", name: "Gambia", iso: "gm" },
  { code: "+221", name: "Senegal", iso: "sn" },
  { code: "+222", name: "Mauritania", iso: "mr" },
  { code: "+223", name: "Mali", iso: "ml" },
  { code: "+224", name: "Guinea", iso: "gn" },
  { code: "+225", name: "Ivory Coast", iso: "ci" },
  { code: "+226", name: "Burkina Faso", iso: "bf" },
  { code: "+227", name: "Niger", iso: "ne" },
  { code: "+228", name: "Togo", iso: "tg" },
  { code: "+229", name: "Benin", iso: "bj" },
  { code: "+230", name: "Mauritius", iso: "mu" },
  { code: "+231", name: "Liberia", iso: "lr" },
  { code: "+232", name: "Sierra Leone", iso: "sl" },
  { code: "+233", name: "Ghana", iso: "gh" },
  { code: "+234", name: "Nigeria", iso: "ng" },
  { code: "+235", name: "Chad", iso: "td" },
  { code: "+236", name: "Central African Republic", iso: "cf" },
  { code: "+237", name: "Cameroon", iso: "cm" },
  { code: "+238", name: "Cape Verde", iso: "cv" },
  { code: "+239", name: "São Tomé & Príncipe", iso: "st" },
  { code: "+240", name: "Equatorial Guinea", iso: "gq" },
  { code: "+241", name: "Gabon", iso: "ga" },
  { code: "+242", name: "Republic of the Congo", iso: "cg" },
  { code: "+243", name: "DR Congo", iso: "cd" },
  { code: "+244", name: "Angola", iso: "ao" },
  { code: "+245", name: "Guinea-Bissau", iso: "gw" },
  { code: "+248", name: "Seychelles", iso: "sc" },
  { code: "+249", name: "Sudan", iso: "sd" },
  { code: "+250", name: "Rwanda", iso: "rw" },
  { code: "+251", name: "Ethiopia", iso: "et" },
  { code: "+252", name: "Somalia", iso: "so" },
  { code: "+253", name: "Djibouti", iso: "dj" },
  { code: "+254", name: "Kenya", iso: "ke" },
  { code: "+255", name: "Tanzania", iso: "tz" },
  { code: "+256", name: "Uganda", iso: "ug" },
  { code: "+257", name: "Burundi", iso: "bi" },
  { code: "+258", name: "Mozambique", iso: "mz" },
  { code: "+260", name: "Zambia", iso: "zm" },
  { code: "+261", name: "Madagascar", iso: "mg" },
  { code: "+262", name: "Réunion", iso: "re" },
  { code: "+263", name: "Zimbabwe", iso: "zw" },
  { code: "+264", name: "Namibia", iso: "na" },
  { code: "+265", name: "Malawi", iso: "mw" },
  { code: "+266", name: "Lesotho", iso: "ls" },
  { code: "+267", name: "Botswana", iso: "bw" },
  { code: "+268", name: "Eswatini", iso: "sz" },
  { code: "+269", name: "Comoros", iso: "km" },
  { code: "+290", name: "Saint Helena", iso: "sh" },
  { code: "+291", name: "Eritrea", iso: "er" },
  { code: "+297", name: "Aruba", iso: "aw" },
  { code: "+298", name: "Faroe Islands", iso: "fo" },
  { code: "+299", name: "Greenland", iso: "gl" },
  { code: "+350", name: "Gibraltar", iso: "gi" },
  { code: "+351", name: "Portugal", iso: "pt" },
  { code: "+352", name: "Luxembourg", iso: "lu" },
  { code: "+353", name: "Ireland", iso: "ie" },
  { code: "+354", name: "Iceland", iso: "is" },
  { code: "+355", name: "Albania", iso: "al" },
  { code: "+356", name: "Malta", iso: "mt" },
  { code: "+357", name: "Cyprus", iso: "cy" },
  { code: "+358", name: "Finland", iso: "fi" },
  { code: "+359", name: "Bulgaria", iso: "bg" },
  { code: "+370", name: "Lithuania", iso: "lt" },
  { code: "+371", name: "Latvia", iso: "lv" },
  { code: "+372", name: "Estonia", iso: "ee" },
  { code: "+373", name: "Moldova", iso: "md" },
  { code: "+374", name: "Armenia", iso: "am" },
  { code: "+375", name: "Belarus", iso: "by" },
  { code: "+376", name: "Andorra", iso: "ad" },
  { code: "+377", name: "Monaco", iso: "mc" },
  { code: "+378", name: "San Marino", iso: "sm" },
  { code: "+380", name: "Ukraine", iso: "ua" },
  { code: "+381", name: "Serbia", iso: "rs" },
  { code: "+382", name: "Montenegro", iso: "me" },
  { code: "+383", name: "Kosovo", iso: "xk" },
  { code: "+385", name: "Croatia", iso: "hr" },
  { code: "+386", name: "Slovenia", iso: "si" },
  { code: "+387", name: "Bosnia & Herzegovina", iso: "ba" },
  { code: "+389", name: "North Macedonia", iso: "mk" },
  { code: "+420", name: "Czech Republic", iso: "cz" },
  { code: "+421", name: "Slovakia", iso: "sk" },
  { code: "+423", name: "Liechtenstein", iso: "li" },
  { code: "+852", name: "Hong Kong", iso: "hk" },
  { code: "+853", name: "Macau", iso: "mo" },
  { code: "+855", name: "Cambodia", iso: "kh" },
  { code: "+856", name: "Laos", iso: "la" },
  { code: "+880", name: "Bangladesh", iso: "bd" },
  { code: "+886", name: "Taiwan", iso: "tw" },
  { code: "+960", name: "Maldives", iso: "mv" },
  { code: "+961", name: "Lebanon", iso: "lb" },
  { code: "+962", name: "Jordan", iso: "jo" },
  { code: "+963", name: "Syria", iso: "sy" },
  { code: "+964", name: "Iraq", iso: "iq" },
  { code: "+965", name: "Kuwait", iso: "kw" },
  { code: "+966", name: "Saudi Arabia", iso: "sa" },
  { code: "+967", name: "Yemen", iso: "ye" },
  { code: "+968", name: "Oman", iso: "om" },
  { code: "+970", name: "Palestine", iso: "ps" },
  { code: "+971", name: "United Arab Emirates", iso: "ae" },
  { code: "+972", name: "Israel", iso: "il" },
  { code: "+973", name: "Bahrain", iso: "bh" },
  { code: "+974", name: "Qatar", iso: "qa" },
  { code: "+975", name: "Bhutan", iso: "bt" },
  { code: "+976", name: "Mongolia", iso: "mn" },
  { code: "+977", name: "Nepal", iso: "np" },
  { code: "+992", name: "Tajikistan", iso: "tj" },
  { code: "+993", name: "Turkmenistan", iso: "tm" },
  { code: "+994", name: "Azerbaijan", iso: "az" },
  { code: "+995", name: "Georgia", iso: "ge" },
  { code: "+996", name: "Kyrgyzstan", iso: "kg" },
  { code: "+998", name: "Uzbekistan", iso: "uz" }

  // { code: "+1", name: "US", iso: "us" },
  // { code: "+7", name: "RU", iso: "ru" },
  // { code: "+20", name: "EG", iso: "eg" },
  // { code: "+27", name: "ZA", iso: "za" },
  // { code: "+30", name: "GR", iso: "gr" },
  // { code: "+31", name: "NL", iso: "nl" },
  // { code: "+32", name: "BE", iso: "be" },
  // { code: "+33", name: "FR", iso: "fr" },
  // { code: "+34", name: "ES", iso: "es" },
  // { code: "+36", name: "HU", iso: "hu" },
  // { code: "+39", name: "IT", iso: "it" },
  // { code: "+40", name: "RO", iso: "ro" },
  // { code: "+41", name: "CH", iso: "ch" },
  // { code: "+43", name: "AT", iso: "at" },
  // { code: "+44", name: "GB", iso: "gb" },
  // { code: "+45", name: "DK", iso: "dk" },
  // { code: "+46", name: "SE", iso: "se" },
  // { code: "+47", name: "NO", iso: "no" },
  // { code: "+48", name: "PL", iso: "pl" },
  // { code: "+49", name: "DE", iso: "de" },
  // { code: "+51", name: "PE", iso: "pe" },
  // { code: "+52", name: "MX", iso: "mx" },
  // { code: "+53", name: "CU", iso: "cu" },
  // { code: "+54", name: "AR", iso: "ar" },
  // { code: "+55", name: "BR", iso: "br" },
  // { code: "+56", name: "CL", iso: "cl" },
  // { code: "+57", name: "CO", iso: "co" },
  // { code: "+58", name: "VE", iso: "ve" },
  // { code: "+60", name: "MY", iso: "my" },
  // { code: "+61", name: "AU", iso: "au" },
  // { code: "+62", name: "ID", iso: "id" },
  // { code: "+63", name: "PH", iso: "ph" },
  // { code: "+64", name: "NZ", iso: "nz" },
  // { code: "+65", name: "SG", iso: "sg" },
  // { code: "+66", name: "TH", iso: "th" },
  // { code: "+81", name: "JP", iso: "jp" },
  // { code: "+82", name: "KR", iso: "kr" },
  // { code: "+84", name: "VN", iso: "vn" },
  // { code: "+86", name: "CN", iso: "cn" },
  // { code: "+90", name: "TR", iso: "tr" },
  // { code: "+91", name: "IN", iso: "in" },
  // { code: "+92", name: "PK", iso: "pk" },
  // { code: "+93", name: "AF", iso: "af" },
  // { code: "+94", name: "LK", iso: "lk" },
  // { code: "+95", name: "MM", iso: "mm" },
  // { code: "+98", name: "IR", iso: "ir" },
  // { code: "+211", name: "SS", iso: "ss" },
  // { code: "+212", name: "MA", iso: "ma" },
  // { code: "+213", name: "DZ", iso: "dz" },
  // { code: "+216", name: "TN", iso: "tn" },
  // { code: "+218", name: "LY", iso: "ly" },
  // { code: "+220", name: "GM", iso: "gm" },
  // { code: "+221", name: "SN", iso: "sn" },
  // { code: "+222", name: "MR", iso: "mr" },
  // { code: "+223", name: "ML", iso: "ml" },
  // { code: "+224", name: "GN", iso: "gn" },
  // { code: "+225", name: "CI", iso: "ci" },
  // { code: "+226", name: "BF", iso: "bf" },
  // { code: "+227", name: "NE", iso: "ne" },
  // { code: "+228", name: "TG", iso: "tg" },
  // { code: "+229", name: "BJ", iso: "bj" },
  // { code: "+230", name: "MU", iso: "mu" },
  // { code: "+231", name: "LR", iso: "lr" },
  // { code: "+232", name: "SL", iso: "sl" },
  // { code: "+233", name: "GH", iso: "gh" },
  // { code: "+234", name: "NG", iso: "ng" },
  // { code: "+235", name: "TD", iso: "td" },
  // { code: "+236", name: "CF", iso: "cf" },
  // { code: "+237", name: "CM", iso: "cm" },
  // { code: "+238", name: "CV", iso: "cv" },
  // { code: "+239", name: "ST", iso: "st" },
  // { code: "+240", name: "GQ", iso: "gq" },
  // { code: "+241", name: "GA", iso: "ga" },
  // { code: "+242", name: "CG", iso: "cg" },
  // { code: "+243", name: "CD", iso: "cd" },
  // { code: "+244", name: "AO", iso: "ao" },
  // { code: "+245", name: "GW", iso: "gw" },
  // { code: "+248", name: "SC", iso: "sc" },
  // { code: "+249", name: "SD", iso: "sd" },
  // { code: "+250", name: "RW", iso: "rw" },
  // { code: "+251", name: "ET", iso: "et" },
  // { code: "+252", name: "SO", iso: "so" },
  // { code: "+253", name: "DJ", iso: "dj" },
  // { code: "+254", name: "KE", iso: "ke" },
  // { code: "+255", name: "TZ", iso: "tz" },
  // { code: "+256", name: "UG", iso: "ug" },
  // { code: "+257", name: "BI", iso: "bi" },
  // { code: "+258", name: "MZ", iso: "mz" },
  // { code: "+260", name: "ZM", iso: "zm" },
  // { code: "+261", name: "MG", iso: "mg" },
  // { code: "+262", name: "RE", iso: "re" },
  // { code: "+263", name: "ZW", iso: "zw" },
  // { code: "+264", name: "NA", iso: "na" },
  // { code: "+265", name: "MW", iso: "mw" },
  // { code: "+266", name: "LS", iso: "ls" },
  // { code: "+267", name: "BW", iso: "bw" },
  // { code: "+268", name: "SZ", iso: "sz" },
  // { code: "+269", name: "KM", iso: "km" },
  // { code: "+290", name: "SH", iso: "sh" },
  // { code: "+291", name: "ER", iso: "er" },
  // { code: "+297", name: "AW", iso: "aw" },
  // { code: "+298", name: "FO", iso: "fo" },
  // { code: "+299", name: "GL", iso: "gl" },
  // { code: "+350", name: "GI", iso: "gi" },
  // { code: "+351", name: "PT", iso: "pt" },
  // { code: "+352", name: "LU", iso: "lu" },
  // { code: "+353", name: "IE", iso: "ie" },
  // { code: "+354", name: "IS", iso: "is" },
  // { code: "+355", name: "AL", iso: "al" },
  // { code: "+356", name: "MT", iso: "mt" },
  // { code: "+357", name: "CY", iso: "cy" },
  // { code: "+358", name: "FI", iso: "fi" },
  // { code: "+359", name: "BG", iso: "bg" },
  // { code: "+370", name: "LT", iso: "lt" },
  // { code: "+371", name: "LV", iso: "lv" },
  // { code: "+372", name: "EE", iso: "ee" },
  // { code: "+373", name: "MD", iso: "md" },
  // { code: "+374", name: "AM", iso: "am" },
  // { code: "+375", name: "BY", iso: "by" },
  // { code: "+376", name: "AD", iso: "ad" },
  // { code: "+377", name: "MC", iso: "mc" },
  // { code: "+378", name: "SM", iso: "sm" },
  // { code: "+380", name: "UA", iso: "ua" },
  // { code: "+381", name: "RS", iso: "rs" },
  // { code: "+382", name: "ME", iso: "me" },
  // { code: "+383", name: "XK", iso: "xk" },
  // { code: "+385", name: "HR", iso: "hr" },
  // { code: "+386", name: "SI", iso: "si" },
  // { code: "+387", name: "BA", iso: "ba" },
  // { code: "+389", name: "MK", iso: "mk" },
  // { code: "+420", name: "CZ", iso: "cz" },
  // { code: "+421", name: "SK", iso: "sk" },
  // { code: "+423", name: "LI", iso: "li" },
  // { code: "+852", name: "HK", iso: "hk" },
  // { code: "+853", name: "MO", iso: "mo" },
  // { code: "+855", name: "KH", iso: "kh" },
  // { code: "+856", name: "LA", iso: "la" },
  // { code: "+880", name: "BD", iso: "bd" },
  // { code: "+886", name: "TW", iso: "tw" },
  // { code: "+960", name: "MV", iso: "mv" },
  // { code: "+961", name: "LB", iso: "lb" },
  // { code: "+962", name: "JO", iso: "jo" },
  // { code: "+963", name: "SY", iso: "sy" },
  // { code: "+964", name: "IQ", iso: "iq" },
  // { code: "+965", name: "KW", iso: "kw" },
  // { code: "+966", name: "SA", iso: "sa" },
  // { code: "+967", name: "YE", iso: "ye" },
  // { code: "+968", name: "OM", iso: "om" },
  // { code: "+970", name: "PS", iso: "ps" },
  // { code: "+971", name: "AE", iso: "ae" },
  // { code: "+972", name: "IL", iso: "il" },
  // { code: "+973", name: "BH", iso: "bh" },
  // { code: "+974", name: "QA", iso: "qa" },
  // { code: "+975", name: "BT", iso: "bt" },
  // { code: "+976", name: "MN", iso: "mn" },
  // { code: "+977", name: "NP", iso: "np" },
  // { code: "+992", name: "TJ", iso: "tj" },
  // { code: "+993", name: "TM", iso: "tm" },
  // { code: "+994", name: "AZ", iso: "az" },
  // { code: "+995", name: "GE", iso: "ge" },
  // { code: "+996", name: "KG", iso: "kg" },
  // { code: "+998", name: "UZ", iso: "uz" }


];

export default countryCodes;
